In [1]:
from pathlib import Path
import scanpy as sc

/home/wenduoc/mambaforge/envs/spatialagent/lib/python3.9/site-packages/xarray_schema/__init__.py:1: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  from pkg_resources import DistributionNotFound, get_distribution
/home/wenduoc/mambaforge/envs/spatialagent/lib/python3.9/site-packages/numba/core/decorators.py:246: RuntimeWarning: nopython is set for njit and is ignored
  warnings.warn('nopython is set for njit and is ignored', RuntimeWarning)

In [2]:


from abc_atlas_access.abc_atlas_cache.abc_project_cache import AbcProjectCache

# Explore data

In [3]:
ad = sc.read_h5ad(
    "/work/magroup/shared/tissueFM/data/Adult_MouseBrain_Zeng/adata_Zeng_C57BL6J-638850.01.h5ad"
)

In [4]:
ad

AnnData object with n_obs × n_vars = 23389 × 550
    obs: 'cells', 'Tissue', 'Technology', 'xcoord', 'ycoord', 'donor_label', 'donor_genotype', 'donor_sex', 'neurotransmitter', 'class', 'subclass', 'supertype', 'cluster'
    var: 'genes'
    obsm: 'spatial'

In [5]:
ad.obs

,cells,Tissue,Technology,xcoord,ycoord,donor_label,donor_genotype,donor_sex,neurotransmitter,class,subclass,supertype,cluster
1015221640100570404,1015221640100570404,C57BL6J-638850.01,MERFISH_Zeng,5.155220,6.507464,C57BL6J-638850,wt/wt,M,Chol,24 MY Glut,261 HB Calcb Chol,1025 HB Calcb Chol_1,4601 HB Calcb Chol_1
1015221640100800173,1015221640100800173,C57BL6J-638850.01,MERFISH_Zeng,5.885817,6.597508,C57BL6J-638850,wt/wt,M,Chol,24 MY Glut,261 HB Calcb Chol,1027 HB Calcb Chol_3,4603 HB Calcb Chol_3
1015221640100360300,1015221640100360300,C57BL6J-638850.01,MERFISH_Zeng,4.151133,5.943029,C57BL6J-638850,wt/wt,M,Glut,24 MY Glut,243 PGRN-PARN-MDRN Hoxb5 Glut,0975 PGRN-PARN-MDRN Hoxb5 Glut_3,4357 PGRN-PARN-MDRN Hoxb5 Glut_3
1015221640100800090,1015221640100800090,C57BL6J-638850.01,MERFISH_Zeng,5.849447,6.544510,C57BL6J-638850,wt/wt,M,Chol,24 MY Glut,261 HB Calcb Chol,1027 HB Calcb Chol_3,4603 HB Calcb Chol_3
1015221640100810318,1015221640100810318,C57BL6J-638850.01,MERFISH_Zeng,6.251264,5.980208,C57BL6J-638850,wt/wt,M,Glut,24 MY Glut,243 PGRN-PARN-MDRN Hoxb5 Glut,0979 PGRN-PARN-MDRN Hoxb5 Glut_7,4404 PGRN-PARN-MDRN Hoxb5 Glut_7
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1015221640100940093,1015221640100940093,C57BL6J-638850.01,MERFISH_Zeng,6.780074,5.365061,C57BL6J-638850,wt/wt,M,,33 Vascular,333 Endo NN,1193 Endo NN_1,5309 Endo NN_1
1015221640200380165,1015221640200380165,C57BL6J-638850.01,MERFISH_Zeng,4.474343,4.877934,C57BL6J-638850,wt/wt,M,,33 Vascular,333 Endo NN,1193 Endo NN_1,5309 Endo NN_1
1015221640100580428,1015221640100580428,C57BL6J-638850.01,MERFISH_Zeng,5.275424,6.142517,C57BL6J-638850,wt/wt,M,,33 Vascular,333 Endo NN,1193 Endo NN_1,5309 Endo NN_1
1015221640100670290,1015221640100670290,C57BL6J-638850.01,MERFISH_Zeng,5.416531,7.222262,C57BL6J-638850,wt/wt,M,,33 Vascular,333 Endo NN,1193 Endo NN_1,5311 Endo NN_1
1015221640200280189,1015221640200280189,C57BL6J-638850.01,MERFISH_Zeng,4.253651,4.367549,C57BL6J-638850,wt/wt,M,,33 Vascular,333 Endo NN,1193 Endo NN_1,5309 Endo NN_1

In [6]:
ad.var

             genes
Prkcq        Prkcq
Col5a1      Col5a1
Grik3        Grik3
Igfbp2      Igfbp2
Osr1          Osr1
...            ...
Blank-33  Blank-33
Blank-34  Blank-34
Blank-45  Blank-45
Blank-23  Blank-23
Blank-48  Blank-48

[550 rows x 1 columns]

In [7]:
ad.obsm["spatial"]

array([[5.15521981, 6.50746439],
       [5.88581734, 6.59750835],
       [4.15113273, 5.943029  ],
       ...,
       [5.27542446, 6.14251707],
       [5.41653116, 7.22226204],
       [4.25365135, 4.36754855]])

In [8]:
ad.X

<23389x550 sparse matrix of type '<class 'numpy.int16'>'
	with 3283876 stored elements in Compressed Sparse Row format>

In [9]:
ad.X.A

array([[2, 0, 1, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [4, 0, 0, ..., 0, 0, 0],
       ...,
       [1, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int16)

# Add region labels

In [10]:
download_base = Path("/work/magroup/shared/agent/data/abc_atlas")
abc_cache = AbcProjectCache.from_cache_dir(download_base)

abc_cache.current_manifest

'releases/20250531/manifest.json'

In [11]:
# cell = abc_cache.get_metadata_dataframe(
#     directory='MERFISH-C57BL6J-638850',
#     file_name='cell_metadata',
#     dtype={"cell_label": str}
# )
# cell.set_index('cell_label', inplace=True)
# print("Number of cells = ", len(cell))
# cell.head(5)

In [12]:
# cell.tail(5)

In [13]:
cell = abc_cache.get_metadata_dataframe(
    directory="MERFISH-C57BL6J-638850",  # MERFISH-C57BL6J-638850
    file_name="cell_metadata",
    dtype={"cell_label": str},
)

In [14]:
cell.set_index("cell_label", inplace=True)
print("Number of cells = ", len(cell))
cell.head(5)

Number of cells =  3938808

,brain_section_label,cluster_alias,average_correlation_score,feature_matrix_label,donor_label,donor_genotype,donor_sex,x,y,z,abc_sample_id
cell_label,,,,,,,,,,,
1019171907102340387-1,C57BL6J-638850.37,1408,0.596276,C57BL6J-638850,C57BL6J-638850,wt/wt,M,7.226245,4.148963,6.6,c9881423-76a7-4835-ba8b-7942fd384b6b
1104095349101460194-1,C57BL6J-638850.26,4218,0.641180,C57BL6J-638850,C57BL6J-638850,wt/wt,M,5.064889,7.309543,4.2,aa815488-6487-4e47-8a5e-d82ac9933bc6
1017092617101450577,C57BL6J-638850.25,4218,0.763531,C57BL6J-638850,C57BL6J-638850,wt/wt,M,5.792921,8.189973,4.0,91ef7a85-8e3e-4410-8ee2-785788df3ebe
1018093344101130233,C57BL6J-638850.13,4218,0.558073,C57BL6J-638850,C57BL6J-638850,wt/wt,M,3.195950,5.868655,2.4,18991e17-fbd3-4ba0-9c60-1281f56ac520
1019171912201610094,C57BL6J-638850.27,4218,0.591009,C57BL6J-638850,C57BL6J-638850,wt/wt,M,5.635732,7.995842,4.4,5e155936-e40d-4c6b-8971-e7fb0079274b

In [15]:
cell

,brain_section_label,cluster_alias,average_correlation_score,feature_matrix_label,donor_label,donor_genotype,donor_sex,x,y,z,abc_sample_id
cell_label,,,,,,,,,,,
1019171907102340387-1,C57BL6J-638850.37,1408,0.596276,C57BL6J-638850,C57BL6J-638850,wt/wt,M,7.226245,4.148963,6.6,c9881423-76a7-4835-ba8b-7942fd384b6b
1104095349101460194-1,C57BL6J-638850.26,4218,0.641180,C57BL6J-638850,C57BL6J-638850,wt/wt,M,5.064889,7.309543,4.2,aa815488-6487-4e47-8a5e-d82ac9933bc6
1017092617101450577,C57BL6J-638850.25,4218,0.763531,C57BL6J-638850,C57BL6J-638850,wt/wt,M,5.792921,8.189973,4.0,91ef7a85-8e3e-4410-8ee2-785788df3ebe
1018093344101130233,C57BL6J-638850.13,4218,0.558073,C57BL6J-638850,C57BL6J-638850,wt/wt,M,3.195950,5.868655,2.4,18991e17-fbd3-4ba0-9c60-1281f56ac520
1019171912201610094,C57BL6J-638850.27,4218,0.591009,C57BL6J-638850,C57BL6J-638850,wt/wt,M,5.635732,7.995842,4.4,5e155936-e40d-4c6b-8971-e7fb0079274b
...,...,...,...,...,...,...,...,...,...,...,...
1018093344100380167-3,C57BL6J-638850.47,5252,0.574988,C57BL6J-638850,C57BL6J-638850,wt/wt,M,1.560003,4.669243,8.8,73bc8aed-8a4a-428d-8d75-c37d41766370
1017165415100930567,C57BL6J-638850.57,5254,0.620546,C57BL6J-638850,C57BL6J-638850,wt/wt,M,5.032556,3.695696,11.0,a137c81a-b2b8-4c85-b967-3ec5753e6833
1017155956102610748,C57BL6J-638850.49,5254,0.548053,C57BL6J-638850,C57BL6J-638850,wt/wt,M,2.549142,4.231188,9.2,4322a30f-c4c4-4f7a-a915-40037c62eaa6
1017155956101980080-1,C57BL6J-638850.50,5252,0.621901,C57BL6J-638850,C57BL6J-638850,wt/wt,M,1.381324,5.784595,9.4,b2c01bcb-5f98-4247-bb74-1ca4667220b5
1018093344102220578-3,C57BL6J-638850.36,5252,0.625139,C57BL6J-638850,C57BL6J-638850,wt/wt,M,6.184499,6.654317,6.4,be0a63d6-7927-414c-a486-ebbf1e722b0b

In [16]:
cell.tail(5)

,brain_section_label,cluster_alias,average_correlation_score,feature_matrix_label,donor_label,donor_genotype,donor_sex,x,y,z,abc_sample_id
cell_label,,,,,,,,,,,
1018093344100380167-3,C57BL6J-638850.47,5252,0.574988,C57BL6J-638850,C57BL6J-638850,wt/wt,M,1.560003,4.669243,8.8,73bc8aed-8a4a-428d-8d75-c37d41766370
1017165415100930567,C57BL6J-638850.57,5254,0.620546,C57BL6J-638850,C57BL6J-638850,wt/wt,M,5.032556,3.695696,11.0,a137c81a-b2b8-4c85-b967-3ec5753e6833
1017155956102610748,C57BL6J-638850.49,5254,0.548053,C57BL6J-638850,C57BL6J-638850,wt/wt,M,2.549142,4.231188,9.2,4322a30f-c4c4-4f7a-a915-40037c62eaa6
1017155956101980080-1,C57BL6J-638850.50,5252,0.621901,C57BL6J-638850,C57BL6J-638850,wt/wt,M,1.381324,5.784595,9.4,b2c01bcb-5f98-4247-bb74-1ca4667220b5
1018093344102220578-3,C57BL6J-638850.36,5252,0.625139,C57BL6J-638850,C57BL6J-638850,wt/wt,M,6.184499,6.654317,6.4,be0a63d6-7927-414c-a486-ebbf1e722b0b

In [17]:
cell.index

Index(['1019171907102340387-1', '1104095349101460194-1', '1017092617101450577',
       '1018093344101130233', '1019171912201610094', '1017092617101300312',
       '1019171912101770241', '1019171910101420741', '1019171910101280057',
       '1104095349101450348',
       ...
       '1018093344201710102-1', '1104095349101170276-1', '1018135614101750622',
       '1019171910102600563', '1015221632100560519', '1018093344100380167-3',
       '1017165415100930567', '1017155956102610748', '1017155956101980080-1',
       '1018093344102220578-3'],
      dtype='object', name='cell_label', length=3938808)

In [18]:
cell.columns

Index(['brain_section_label', 'cluster_alias', 'average_correlation_score',
       'feature_matrix_label', 'donor_label', 'donor_genotype', 'donor_sex',
       'x', 'y', 'z', 'abc_sample_id'],
      dtype='object')

In [19]:
ad.obs = ad.obs.join(cell[["brain_section_label"]], on="cells")
ad.obs["brain_section_label"] = ad.obs["brain_section_label"].astype("category")

In [20]:
ad.obs

,cells,Tissue,Technology,xcoord,ycoord,donor_label,donor_genotype,donor_sex,neurotransmitter,class,subclass,supertype,cluster,brain_section_label
1015221640100570404,1015221640100570404,C57BL6J-638850.01,MERFISH_Zeng,5.155220,6.507464,C57BL6J-638850,wt/wt,M,Chol,24 MY Glut,261 HB Calcb Chol,1025 HB Calcb Chol_1,4601 HB Calcb Chol_1,C57BL6J-638850.01
1015221640100800173,1015221640100800173,C57BL6J-638850.01,MERFISH_Zeng,5.885817,6.597508,C57BL6J-638850,wt/wt,M,Chol,24 MY Glut,261 HB Calcb Chol,1027 HB Calcb Chol_3,4603 HB Calcb Chol_3,C57BL6J-638850.01
1015221640100360300,1015221640100360300,C57BL6J-638850.01,MERFISH_Zeng,4.151133,5.943029,C57BL6J-638850,wt/wt,M,Glut,24 MY Glut,243 PGRN-PARN-MDRN Hoxb5 Glut,0975 PGRN-PARN-MDRN Hoxb5 Glut_3,4357 PGRN-PARN-MDRN Hoxb5 Glut_3,C57BL6J-638850.01
1015221640100800090,1015221640100800090,C57BL6J-638850.01,MERFISH_Zeng,5.849447,6.544510,C57BL6J-638850,wt/wt,M,Chol,24 MY Glut,261 HB Calcb Chol,1027 HB Calcb Chol_3,4603 HB Calcb Chol_3,C57BL6J-638850.01
1015221640100810318,1015221640100810318,C57BL6J-638850.01,MERFISH_Zeng,6.251264,5.980208,C57BL6J-638850,wt/wt,M,Glut,24 MY Glut,243 PGRN-PARN-MDRN Hoxb5 Glut,0979 PGRN-PARN-MDRN Hoxb5 Glut_7,4404 PGRN-PARN-MDRN Hoxb5 Glut_7,C57BL6J-638850.01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1015221640100940093,1015221640100940093,C57BL6J-638850.01,MERFISH_Zeng,6.780074,5.365061,C57BL6J-638850,wt/wt,M,,33 Vascular,333 Endo NN,1193 Endo NN_1,5309 Endo NN_1,C57BL6J-638850.01
1015221640200380165,1015221640200380165,C57BL6J-638850.01,MERFISH_Zeng,4.474343,4.877934,C57BL6J-638850,wt/wt,M,,33 Vascular,333 Endo NN,1193 Endo NN_1,5309 Endo NN_1,C57BL6J-638850.01
1015221640100580428,1015221640100580428,C57BL6J-638850.01,MERFISH_Zeng,5.275424,6.142517,C57BL6J-638850,wt/wt,M,,33 Vascular,333 Endo NN,1193 Endo NN_1,5309 Endo NN_1,C57BL6J-638850.01
1015221640100670290,1015221640100670290,C57BL6J-638850.01,MERFISH_Zeng,5.416531,7.222262,C57BL6J-638850,wt/wt,M,,33 Vascular,333 Endo NN,1193 Endo NN_1,5311 Endo NN_1,C57BL6J-638850.01
1015221640200280189,1015221640200280189,C57BL6J-638850.01,MERFISH_Zeng,4.253651,4.367549,C57BL6J-638850,wt/wt,M,,33 Vascular,333 Endo NN,1193 Endo NN_1,5309 Endo NN_1,C57BL6J-638850.01

In [22]:
# sanity check
n_missing = int(ad.obs["brain_section_label"].isna().sum())
print(
    f"Assigned brain_section_label to {ad.n_obs - n_missing}/{ad.n_obs} cells; {n_missing} missing."
)

Assigned brain_section_label to 23389/23389 cells; 0 missing.